- name: Setup backend
  hosts: server_role_redis_server
  become: true
  gather_facts: yes

  vars:
    ansible_user: rocky
  roles:
    - backend

- name: Setup frontend
  hosts: server_role_frontend_server
  become: true
  gather_facts: yes
  vars:
    ansible_user: ubuntu
  roles:
    - frontend
