- name: Setup backend
  hosts: all
  become: true
  gather_facts: yes

  vars:
    ansible_user: 'rocky'
  roles:
    - backend

- name: Setup frontend
  hosts: all
  become: true
  gather_facts: yes
  vars:
    ansible_user: 'ubuntu'
  roles:
    - frontend
